routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return redirect()->route('error');
});

/*
 * Routes for preview emails on browser
 */
//Route::get('/preview-notification', function () {
//
//    $message = (new \App\Notifications\WhoWannabeSanta())->toMail('ionut.trofin@grapefruit.ro');
//
//    $markdown = new \Illuminate\Mail\Markdown(view(), config('mail.markdown'));
//    return $markdown->render('vendor.notifications.email', $message->toArray());
//});
//
//Route::get('/preview-notification-santa', function () {
//
//    $message = (new \App\Notifications\NotifySanta(\App\Grapefruiteer::first()))->toMail('ionut.trofin@grapefruit.ro');
//
//    $markdown = new \Illuminate\Mail\Markdown(view(), config('mail.markdown'));
//    return $markdown->render('vendor.notifications.email', $message->data());
//});

Route::get('/import', 'SantaController@import')->name('get.import');
Route::post('/import', 'SantaController@importUsers')->name('post.import');

Route::get('/wannabe-santa/{id}', 'SantaController@index')->name('index');
Route::post('/wannabe-santa', 'SantaController@store')->name('pick');

Route::get('/good-santa', 'SantaController@success')->name('success');
Route::get('/bad-santa', 'SantaController@error')->name('error');

Route::get('/notifyGrapefruiteers', 'SantaController@notifyGrapefruiteers');


Route::group(['prefix' => 'xmas2019', 'as' => 'xmas2019.'], function(){
    Route::get('/import', 'XmasController@import')->name('get.import');
    Route::post('/import', 'XmasController@importUsers')->name('post.import');

    Route::get('/wannabe-santa/{id}', 'XmasController@index')->name('index');
    Route::post('/wannabe-santa', 'XmasController@store')->name('pick');

    Route::get('/good-santa', 'XmasController@success')->name('success');
    Route::get('/bad-santa', 'XmasController@error')->name('error');

    Route::get('/notifySantas', 'XmasController@notifySantas');
});

resources/views/xmas2019/error.blade.php
@extends('xmas2019.layout')

@section('content')
    <!--  Step 2  -->
    <div class='cracker' id='cracker'>
        <div class='cracker-message'>
            <div class='cracker-message__inner'>
                Ho Ho Ho, 404 !
            </div>
        </div>
        <div class='cracker-left'>
            <div class='cracker-left-inner'>
                <div class='cracker-left__mask-top'></div>
                <div class='cracker-left__mask-bottom'></div>
                <div class='cracker-left__tail'></div>
                <div class='cracker-left__end'></div>
                <div class='cracker-left__body'></div>
                <div class='cracker-left-zigzag'>
                    <div class='cracker-left-zigzag__item'></div>
                    <div class='cracker-left-zigzag__item'></div>
                    <div class='cracker-left-zigzag__item'></div>
                    <div class='cracker-left-zigzag__item'></div>
                    <div class='cracker-left-zigzag__item'></div>
                </div>
            </div>
        </div>
        <div class='cracker-right'>
            <div class='cracker-right-inner'>
                <div class='cracker-right__mask-top'></div>
                <div class='cracker-right__mask-bottom'></div>
                <div class='cracker-right__tail'></div>
                <div class='cracker-right__end'></div>
                <div class='cracker-right__body'></div>
                <div class='cracker-right-zigzag'>
                    <div class='cracker-right-zigzag__item'></div>
                    <div class='cracker-right-zigzag__item'></div>
                    <div class='cracker-right-zigzag__item'></div>
                    <div class='cracker-right-zigzag__item'></div>
                    <div class='cracker-right-zigzag__item'></div>
                </div>
            </div>
        </div>
    </div>
    <p class='hover-me-text'>Deschide bomboana</p>
@endsection

resources/views/xmas2019/import.blade.php
<!doctype html>
<html lang="{{ app()->getLocale() }}">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Laravel</title>

    <!-- Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,600" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <style>
        html, body {
            background-color: #fff;
            color: #636b6f;
            font-family: 'Raleway', sans-serif;
            font-weight: 100;
            height: 100vh;
            margin: 0;
        }

        .full-height {
            height: 100vh;
        }

        .flex-center {
            align-items: center;
            display: flex;
            justify-content: center;
        }

        .position-ref {
            position: relative;
        }

        .top-right {
            position: absolute;
            right: 10px;
            top: 18px;
        }

        .content {
            text-align: center;
        }

        .title {
            font-size: 84px;
        }

        .links > a {
            color: #636b6f;
            padding: 0 25px;
            font-size: 12px;
            font-weight: 600;
            letter-spacing: .1rem;
            text-decoration: none;
            text-transform: uppercase;
        }

        .m-b-md {
            margin-bottom: 30px;
        }
    </style>
</head>
<body>
<div class="flex-center position-ref full-height">

    <div class="content">
        <div class="title m-b-md">
            Secret Santa
        </div>
    <form method="post" action="{{ route('xmas2019.post.import') }}"  enctype="multipart/form-data">
        {{ csrf_field() }}
        <input class="form-control-file" type="file" name="base" id="file">
        <button type="submit ">Import Santas</button>
    </form>
    <ul>
        @forelse($santas as $santa)
            <li>{{ $santa->first_name. ' ' . $santa->last_name . '  ' . $santa->email  }}</li>
        @empty
            <li> No Santas </li>
        @endforelse
    </ul>


    </div>
</div>
</body>
</html>

resources/views/xmas2019/index.blade.php
@extends('xmas2019.layout')

@section('content')
    <!--  Step 1  -->
    <div class="window">
        <div class="santa">
            <div class="head">
                <div class="face">
                    <div class="redhat">
                        <div class="whitepart"></div>
                        <div class="redpart"></div>
                        <div class="hatball"></div>
                    </div>
                    <div class="eyes"></div>
                    <div class="beard">
                        <div class="nouse"></div>
                        <div class="mouth"></div>
                    </div>
                </div>
                <div class="ears"></div>
            </div>
            <div class="body"></div>
        </div>
    </div>

    <div class="message">
        <h1>Secret Santa!</h1>
        <h1>{{ $wannabeSanta->first_name . ' ' . $wannabeSanta->last_name }}</h1>


        <h2 class="copyright">Vrei sa aduci bucurie?</h2>
{{--        <h2 class="copyright">Cine vrea să fie Moș Crăciun în locul meu?</h2>--}}
        <form method="post" action="{{ route('xmas2019.pick') }}">
            {{ csrf_field() }}
{{--            <select name="santa" class="select">--}}
{{--                <option value="" disabled selected>Cine vrea să fie Moș Crăciun în locul meu?</option>--}}
{{--                @foreach($wannabeSanta as $santa)--}}
{{--                    <option value="{{ $santa->id }}">{{ $santa->first_name . ' ' . $santa->last_name }}</option>--}}
{{--                @endforeach--}}
{{--            </select>--}}

            <input type="hidden" name="santa" class="select" value="{{ $wannabeSanta->hash }}">
            <button type="submit" class="button">Vreau</button>
        </form>
    </div>
@endsection()

resources/views/xmas2019/layout.blade.php
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Secret Santa - Grapefruit</title>

    <link href="{{ asset('assets/style.css') }}" rel="stylesheet" type="text/css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"
            type="text/javascript"></script>

</head>
<body>

<canvas id="canvas"></canvas>
@yield('content')

<script src="{{ asset('assets/js/jquery-3.4.1.min.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/main.js') }}" type="text/javascript"></script>
</body>
</html>

resources/views/xmas2019/success.blade.php
@extends('xmas2019.layout')

@section('content')
    <!--  Step 2  -->
    <div class='cracker' id='cracker'>
        <div class='cracker-message'>


            <div class='cracker-message__inner'>
                @if (session('theChosenOne'))
                    {{ session('theChosenOne')->first_name. ' ' . session('theChosenOne')->last_name }}
                @else
                    {{ 404 }}
                @endif
            </div>
        </div>
        <div class='cracker-left'>
            <div class='cracker-left-inner'>
                <div class='cracker-left__mask-top'></div>
                <div class='cracker-left__mask-bottom'></div>
                <div class='cracker-left__tail'></div>
                <div class='cracker-left__end'></div>
                <div class='cracker-left__body'></div>
                <div class='cracker-left-zigzag'>
                    <div class='cracker-left-zigzag__item'></div>
                    <div class='cracker-left-zigzag__item'></div>
                    <div class='cracker-left-zigzag__item'></div>
                    <div class='cracker-left-zigzag__item'></div>
                    <div class='cracker-left-zigzag__item'></div>
                </div>
            </div>
        </div>
        <div class='cracker-right'>
            <div class='cracker-right-inner'>
                <div class='cracker-right__mask-top'></div>
                <div class='cracker-right__mask-bottom'></div>
                <div class='cracker-right__tail'></div>
                <div class='cracker-right__end'></div>
                <div class='cracker-right__body'></div>
                <div class='cracker-right-zigzag'>
                    <div class='cracker-right-zigzag__item'></div>
                    <div class='cracker-right-zigzag__item'></div>
                    <div class='cracker-right-zigzag__item'></div>
                    <div class='cracker-right-zigzag__item'></div>
                    <div class='cracker-right-zigzag__item'></div>
                </div>
            </div>
        </div>
    </div>
    <p class='hover-me-text'>Deschide bomboana</p>
@endsection